<?php /* Template Name: terms-page qbic */ ?>
<?php get_header();?>
<!-- For variable Which comes from DATA base, I use ACF. -->
<main role="main" class="terms-page">
    <nav class="breadcrumb container m-auto py-4 flex flex-row items-center gap-6">
        <a href="/" class="font-bold text-base">Home</a>
        <svg width="20" height="12" viewBox="0 0 20 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M3.7525 1.5L8.25 6.0135L3.75 10.5" stroke="#778686" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M11.7525 1.5L16.25 6.0135L11.75 10.5" stroke="#778686" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <span>Terms of Service</span>
    </nav>
    <section class="relative w-full">
        <div class="sidebar absolute top-0 left-0 pr-2 lg:pl-10 xl:pl-16 xxl:pl-35 pt-4 xl:pt-6 xxl:pt-8 pb-12 font-semibold text-lg hidden lg:flex">
            <div class="container m-auto lg:flex flex-col gap-5">
                <span class="font-extrabold">Sections</span>
                <ul class="flex flex-col gap-6 list-inside list-decimal">
                    <li><a href="#msa">Applicability of this MSA</a></li>
                    <li><a href="#service">Service Offerings</a></li>
                    <li><a href="#commitments">Qbic Commitments</a></li>
                    <li><a href="#responsibilities">Your Responsibilities</a></li>
                    <li><a href="#obligations">Financial Obligations</a></li>
                    <li><a href="#intellectual">Intellectual Property</a></li>
                    <li><a href="#licenses">Data and Intellectual Property Licenses</a></li>
                    <li><a href="#appointment">Appointment of Third Party Service Providers</a></li>
                    <li><a href="#warranties">Warranties, Representations, and Disclaimer</a></li>
                    <li><a href="#indemnification">Indemnification</a></li>
                    <li><a href="#limitation">Limitation of Liabilities</a></li>
                    <li><a href="#dispute">Dispute Resolution</a></li>
                    <li><a href="#confidential">Confidential Information</a></li>
                    <li><a href="#termination">Term and Termination</a></li>
                    <li><a href="#cooperation">Cooperation</a></li>
                    <li><a href="#contractor">Independent Contractor Relationship</a></li>
                    <li><a href="#assignment">Assignment</a></li>
                    <li><a href="#force-majeure">Force Majeure</a></li>
                    <li><a href="#restrictions">Trade Restrictions</a></li>
                    <li><a href="#governing">Governing Law and Jurisdiction</a></li>
                    <li><a href="#government-customers">Government Customers</a></li>
                    <li><a href="#disclosure">Disclosure to Law Enforcement or Judicial Proceedings</a></li>
                    <li><a href="#waiver">Waiver</a></li>
                    <li><a href="#severability">Severability</a></li>
                    <li><a href="#construction">Construction</a></li>
                    <li><a href="#agreement">Entire Agreement</a></li>
                    <li><a href="#definitions">Definitions</a></li>
                </ul>
            </div>
        </div>
        <div class="terms-content container m-auto flex flex-row justify-end mb-16">
            <div class="w-full lg:w-3/5 xxl:w-2/3 lg:pl-3 xl:pl-8 xxl:pl-16 flex flex-col gap-10 lg:gap-20">
                <div class="flex flex-col items-center lg:items-start">
                    <h1 class="text-3xl lg:text-5xl font-bold text-center lg:text-left flex flex-col lg:flex-row items-center lg:gap-4"><span>Terms </span><span>of Service</span></h1>
                    <span class="text-lg date text-center lg:text-left">Updated January 2022</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Welcome to the Qbic website and our ecosystem of services, products, and resources (collectively the “Services”). In order to align your expectations with Qbic’s ability to provide the Services, all subscribers, users, and visitors are required to accept the legally binding responsibilities and obligations in the Qbic Terms of Service, including without limitation those provisions contained in this master services agreement (the “MSA”). 
                        Please read the Terms of Service carefully before using any Service. By using or continuing to use a Service, you accept and consent to the rights, obligations, and practices described in this MSA.
                    </p>
                </div>
                <div>
                    <span class="text-2xl font-extrabold">Basic Terms</span>
                    <p class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        This MSA is a legally binding agreement between you and Qbic (“Qbic,” "we," "us," or "our") to which, as conditions precedent to offering you, or the person or entity you represent (“you,” or “your”), any Service, you expressly affirm the accuracy of each of the following statements: 
                        You are lawfully able to enter into contracts in both the United States of America and the jurisdiction in which you presently reside;
                        You are authorized to enter into this MSA on your behalf or on behalf of the person or entity you represent;
                    </p>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li>You consent to the application of the laws of the State of New Jersey, United States of America (“US”) and its sole jurisdiction therein;</li>
                        <li>You shall be responsible for ensuring the accuracy of your contact and billing addresses, as indicated in your Account, at all times;</li>
                        <li>You authorize us to appoint our affiliates, subprocessors, and third party service providers to provide ordinary and necessary data processing services related to the Services;</li>
                        <li>You consent to resolve all Disputes arising from or related to the Services in accordance to the Terms of Service and in your individual capacity;</li>
                        <li>You will immediately notify us in the event your use of any Service is for a non-business purpose; and</li>
                        <li>You consent to and shall abide by the Terms of Service at all times.</li>
                    </ul>
                    <p class="mt-4 lg:font-medium text-xl lg:text-2xl">For your convenience, certain terms used in this MSA are defined in <span class="font-medium lg:font-bold">Section 27</span>, or as otherwise first indicated. This MSA shall replace any previously applicable agreements as of the Effective Date.</p>
                </div>
                <div id="msa">
                    <span class="block text-2xl font-extrabold">Specific Terms</span>
                    <span class="block mt-6 text-2xl lg:text-4xl font-bold">1.	Applicability of this MSA</span>
                    <p class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        This MSA provides the general terms, conditions, and the framework within which you, your Representatives, your End Users, and the End Users of your Representatives (collectively “Covered Users”) may Process and use the Services. By mutual written agreement, the Parties may enter into one or more Data Processing Addenda, Service Level Addenda, Supplemental Program Addenda, Supplemental Use Policies, and/or Service Orders to specify additional terms and conditions with respect to any Service or Program provided by Qbic. For purposes of clarity, a DPA shall generally detail the methodology of how data is Processed by Qbic; a SLA shall generally detail the reliability and remedies for deficiency of an applicable Service or Program; a SPA shall generally detail the obligations and responsibilities for participating in an applicable Program; a SUP shall refer to any policy governing the use of the Services; and a Service Order shall generally detail the type and quantity of Service being requested. In the event of a conflict between the terms of a DPA, SLA, SPA, SUP, Service Order and this MSA, the controlling priority of the documents will be in the following order (in decreasing priority): the DPA, SUP, SPA, Service Order, SLA, and this MSA. In the event that you previously entered into an agreement with Qbic (an “Existing Terms of Service”), then such Existing Terms of Service shall automatically terminate without any further action by either Party on the Effective Date.
                    </p>
                </div>
                <div id="service">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">2.	Service Offerings</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">License to the Services.</span> For the Term, and subject to the Terms of Service, Qbic grants you a limited, time-bound, revocable, non-exclusive, non-sublicensable, non-transferable, non-assignable license to use the Services in furtherance of your business purposes.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Registration.</span> The Services can only be accessed after the creation of an Account. You may create an Account by providing Qbic with certain information, including contact information, log-in credentials, payment, and billing sources (collectively “Registration Information”) and after authentication by Qbic.  You agree that you shall update and ensure that your Registration Information is current and accurate at all times. You agree that you shall not disclose, transfer, license, or otherwise share your Account authentication without Qbic’s prior written consent in each instance.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Account Activities.</span> The Services are designed to serve as a tool or utility in which Covered Users have broad discretion to Process Covered User Data. Accordingly, unless and to the extent that an event is caused by Qbic’s failure to provide the Services in accordance with its obligations expressly assumed under this MSA, you are solely responsible and liable for all activities that are affiliated or associated with your Account, including without limitation: (i) the Processing of all Covered User Data; (ii) any Data Processed by any Covered User arising from or related to the Services; (iii) and any Data displayed, disclosed, generated, and/or published arising from or related to a Covered User’s use of the Services.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Support.</span> You have complimentary access to Qbic’s standard technical support (hereafter, “Support”), which consists of 24x7 telephone and online availability regarding the standard, as-is operations of any Service. You are directly responsible for providing support to all other Covered Users. Without limitation, Qbic does not offer or provide support: (i) for application-specific issues such as application configuration, CGI programming, web server, mail server, database configuration, or any other such issue; (ii) for issues related to the development, maintenance, operation, or other administration of Covered User Data; and/or (iii) to any End User Support. Qbic reserves the right to modify Support availability from time to time, and such changes will be effective ten (10) days after Notice.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Open Source Software.</span> You recognize and agree that the Services are provided with, or facilitated by, certain open source software.  The use of such open source software is subject to the applicable open source license terms which are either: (i) presented with the applicable Services; or (ii) readily accessible from within the applicable software or from a publicly-available source, in which case you shall be responsible to access, review, and abide by all such license terms prior to any use of the corresponding software.  By using the Services, you agree to comply with and be bound by the above terms and conditions governing the use of certain open source software programs.</li>
                    </ul>
                </div>
                <div id="commitments">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">3.	Qbic Commitments</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Provision of Services.</span> Qbic shall provide the Services in a professional and workmanlike manner. Qbic shall not have any proprietary rights to any Data that is Processed by Covered Users.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Privacy.</span> Qbic complies and operates under various privacy frameworks between the US and the international community which in part requires online service providers like Qbic to protect personal Data of Covered Users from disclosure, subject to actions that satisfy legal due process and your consent (collectively the “Privacy Frameworks”).</li>
                        <li><span class="font-bold" style="color:#FF2255;">Processing.</span> Qbic will allow you to determine where and how you wish to Process Covered User Data, provided that all Covered Users comply with the Terms of Service.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Security.</span> Subject to Sections 2, 3, 4, 7, 9, and 11, Qbic will implement reasonable and appropriate measures to secure Covered User Data against accidental or unauthorized access, transmission, loss or disclosure. Unless otherwise expressly specified by an applicable Service Order, Qbic shall have no obligation to maintain Covered User Data, backup Covered User Data, or otherwise store Customer Data on behalf of any Covered User.</li>
                    </ul>
                </div>
                <div id="responsibilities">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">4.	Your Responsibilities</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Use of Services.</span> You shall be responsible for all Data that is Processed by any Covered User and the otherwise use of the Services by a Covered User.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Covered Users.</span> You control all Processing of Covered User Data and in your discretion, may permit other Covered Users to access the Services, subject to and in compliance with the Terms of Service. The number and/or types of Covered Users may be limited if and to the extent specified in a Service Order or SPA. Unless otherwise expressly permitted in this MSA, you shall not, and shall ensure that no Covered Users (unless, and solely to the extent permitted by the terms of an applicable open source license): (i) modify, reverse engineer, decompile, disassemble, copy, distribute, sublicense, sell, resell, lease, create derivative works based on, or otherwise exploit all or any software-related portion of the Services; or (ii) appoint, authorize, or permit anyone to license, sublicense, or distribute the Services to any third party, or permit any unauthorized third party to access or use, all or any portion of the Services. At all times, you shall be responsible for ensuring that all Covered Users (i) comply with the Terms of Service and (ii) are notified of the existence, modification and/or amendment of the Terms of Service.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Configuration of the Services.</span> You shall ensure that the Services are properly configured for your purposes and shall take reasonable steps for securing and protecting Covered User Data. Without limiting Qbic’s data security obligations hereunder, you shall ensure that your configuration of the Services contain appropriate and industry standard physical, administrative, and technical safeguards (including the use of firewalls, encryption, and other tools) to protect against breach, disclosure, or unauthorized access of Covered User Data and/or other Data that is Processed by any Covered User in connection with the Services, including without limitation any safeguards required by applicable data security and/or data privacy laws. You shall be responsible and liable for the activities of any individual or entity who gains access to Covered User Data or the Services as a result of your failure to comply with the obligations of this subsection.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Resale Prohibited.</span> Covered Users are prohibited from selling or reselling any Service unless you, on behalf of yourself and all Covered Users, consent to the appropriate reseller SUP or SPA without exception.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Third Party Tools and Content.</span> You shall be responsible for ensuring that all third party tools, content, and otherwise components added by you to any Service (collectively “Third Party Content”) shall conform to the Terms of Service, including without limitation Third Party Content made available to you on the Qbic Marketplace. Third Party Content on the Qbic Marketplace is made available to you by TSPs and not from Qbic and may be subject to fees or costs imposed by third party service providers. It is your sole responsibility to ensure that Third Party Content used by you is fit for your purposes. You acknowledge and agree that Qbic is not responsible for any Third Party Content Processed by any Covered User, and that the use of Third Party Content by any Covered User is at your sole and absolute risk. Qbic may, at our sole discretion, prohibit the use of any Third Party Content at any time.YOU ACKNOWLEDGE AND AGREE THAT WITH RESPECT TO THIRD PARTY CONTENT, Qbic IS NOT PARTY TO ANY TRANSACTIONS BETWEEN YOU AND THE APPLICABLE TSP, AND THAT IN THE EVENT OF A DISPUTE BETWEEN YOU AND AN APPLICABLE TSP, YOU IRREVOCABLY RELEASE Qbic FROM ANY AND ALL DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, REGULATORY, OR CONSEQUENTIAL DAMAGES ARISING FROM OR RELATED TO THIRD PARTY CONTENT.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Data Continuity.</span> You shall be solely responsible for backing up all Covered User Data unless you have purchased backup services from Qbic, in which event Qbic will provide backup services to the extent described in the applicable Service Order for the applicable period.</li>
                    </ul>
                </div>
                <div id="obligations">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">5.	Financial Obligations</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Fees and Payment.</span> Qbic shall calculate, invoice, and charge Fees on a daily, weekly, or monthly basis. By accessing, using, or allowing Covered Users to access or use the Account or any Services, you agree that Qbic is permitted to automatically charge the payment mechanism associated with the Account. Payment for all Fees are due within three (3) days of invoicing and shall be paid to Qbic without setoff, counterclaim, deduction, or withholding. Failure to entirely pay all Fees on a timely basis will result in loss of access to the Account and Service interruption. In the event that you fail to entirely satisfy payment to Qbic within thirty (30) days of an invoice, you agree that Qbic may, at Qbic’s sole and absolute discretion, take any action Qbic deems necessary to recover payment, including, without limitation, the use of third party collection agencies. Late payments may result in the accrual of three (3%) percent interest per month (or the highest interest rate permitted by law if less). Without limiting any rights of your rights to receive SLA credits, all Fees are non-cancelable and non-refundable. All Fees shall be priced, invoiced, and paid in US dollars.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Changes in Fees.</span> Qbic may increase, decrease, or add new Fees for any Service by giving you thirty (30) days advance notice.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Third Party Fees.</span> Qbic shall not be responsible for any bank fees, interest charges, overdraft charges or other fees resulting from your payment of an invoice. Currency exchange settlements will be based on agreements between you and your financial services provider.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Credits.</span> Prorated credits may be issued by Qbic to you in the event you retain any active Services and have submitted a credit request to Qbic due to (i) Qbic’s inability to satisfy the Terms of Service or (ii) your downgrade or cancellation of a pre-paid Service. Credit requests can be submitted via your Account, and all credits shall be applied strictly against the monthly payment due for the payment period in which the credits were earned.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Refunds.</span> Prorated refunds may be issued by Qbic to you in the event you cease to retain active Services, provided that (i) you submit a refund request via the cancellation form found in your Account and (ii) only payments made within one hundred eighty (180) days of a properly submitted cancellation form shall be eligible for a refund. In addition to the foregoing, all refunds shall be (i) subject to a five ($5.00) dollar service charge and (ii) issued to the payment method in which the corresponding payment was received by Qbic from you. In the event an originating payment mechanism is not valid or expired at the time of a refund request, Qbic is only able to issue a refund, if any, to the financial institution responsible for the originating payment mechanism.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Taxes.</span> Fees do not include, and you shall promptly pay all sales, use, value-added, consumption, and other applicable taxes and duties arising from or related to the Services, this MSA, or any applicable Service Order or SPA. If any withholding tax is required on any payment, you shall pay such additional amounts as are required so that the net amount received by Qbic is equal to the amount then due and payable. You shall provide Qbic with all reasonable information and documentation requested by Qbic regarding the taxes which are or were due (or which may be due) under this MSA.</li>
                    </ul>
                </div>
                <div id="intellectual">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">6.	Intellectual Property</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Reservation of Rights.</span> As between the Parties, Qbic retains all right, title, and interest in and to the Qbic technology, Confidential Information, Intellectual Property, Proprietary Information, and all modifications, alterations, derivative works, and enhancements thereto and all Qbic Intellectual Property Rights contained therein.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Ownership Rights.</span> All Intellectual Property and related material, including without limitation, any trade secrets, moral rights, goodwill, relevant registrations, or applications for registration, and rights in any patent, copyright, trademark, trade dress, industrial design, and trade name that is developed or produced by Qbic shall be the sole property of Qbic. The use of Qbic Intellectual Property by a Covered User shall be strictly limited to the Term for the Services arising out of or relating to the Terms of Service, and shall not be used by any Covered User for any other reason. You shall be responsible for any and all damages resulting from the unauthorized use of Qbic Intellectual Property.</li>
                    </ul>
                </div>
                <div id="licenses">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">7.	Data and Intellectual Property Licenses</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Identification of the Parties.</span> Each Party may use the name and logo of the other Party to factually identify Qbic as the provider of the Services or that you are a Qbic customer and may make no other use of any of such other Party’s Intellectual Property without such other Party’s prior written consent in each instance. Without limitation, the Parties shall not misrepresent or embellish the relationship between you and Qbic. Each Party may terminate the other Party’s right to use the applicable Party’s name, logo, and any other marks at any time immediately upon valid Notice.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Feedback.</span> In the event you provide Qbic with any suggestions, specifications, comments, information or other feedback, from time to time, with respect to any Qbic Service or SPA (collectively, “Feedback”), you hereby: (i) irrevocably grant Qbic a universal, paid-up, royalty-free, perpetual, transferable license to any and all rights you may have with respect to all Feedback; and (ii) acknowledge that Qbic may utilize Feedback in any manner or media as Qbic may wish in Qbic’s sole discretion.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Use of Data.</span> You expressly grant Qbic the right to Process Covered User Data: (i) as necessary to provide the Services (including by disclosing such Covered User Data to third parties that support the provision of the Services); (ii) as otherwise expressly permitted by the Terms of Service; or (iii) as required by law, regulation, court order, subpoena, or governmental authority. You are responsible for obtaining all necessary rights and consents (including such rights and consents for all Covered Users) for Qbic to Process Covered User Data for the purposes of providing the Services and for meeting Qbic’s obligations under the Terms of Service. In addition, you grant Qbic a license to de-personalize and aggregate any of the Covered User Data to determine usage trends, perform analytics, improve the Services, promote and market the effectiveness of the Services, or for any other ordinary business purpose, provided that such uses shall relate to Qbic’s obligations to provide the Services to you. Qbic shall have no obligation or liability in connection with any use of Covered User Data which is anonymized or otherwise de-personalized, unless, and to the extent, restricted by applicable law.</li>
                    </ul>
                </div>
                <div id="appointment">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">8.	Appointment of Third Party Service Providers</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Certain of Qbic’s obligations under the Terms of Service may be performed by Third Party Service Providers. The responsibilities, obligations, and the rights of the Parties with respect to the use of Third Party Service Providers are provided in the DPA and Privacy Policy. In addition, you agree that Qbic and Qbic’s TSPs may Process Covered User Data in locations other than a Covered User’s country, provided that:
                    </p>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li>You expressly grant Qbic authorization for Qbic to appoint TSPs to provide the Services, including without limitation, third party data center, development, production, maintenance, marketing, financing, and customer support providers in connection with any Service;</li>
                        <li>Qbic will provide you with a list of Qbic’s TSPs that relate to your use of a Service upon request. If you have a reasonable objection to a TSP which relates to your use of a Service, you must notify Qbic of your objection in writing and Qbic will respond within thirty (30) days of such request (each a “TSP Request”). Qbic, at Qbic’s sole and absolute discretion, shall determine if Qbic is able to provide the applicable Service without the use of the applicable TSP. If Qbic is unable to reasonably satisfy your concerns within ninety (90) days of a TSP Request, you may terminate your Account and request prorated credits or refunds in accordance with the Terms of Service. Your failure to provide written objections or requests within any of the deadlines provided in this section will be deemed to be a waiver of the applicable TSP Request; and</li>
                        <li>Qbic shall ensure that Qbic TSPs shall only be engaged by a written contract that imposes processing terms which are substantially no less protective of the Covered User Data than the Terms of Service.</li>
                    </ul>
                </div>
                <div id="warranties">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">9.	Warranties, Representations, and Disclaimer</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Joint.</span> Each Party represents and warrants to the other that: (i) it has all requisite power and authority to enter into this MSA and perform the obligations set forth herein; and (ii) the execution of this MSA and the performance of its obligations and duties hereunder do not and will not violate any agreement to which it is a Party or by which it is bound.</li>
                        <li><span class="font-bold" style="color:#FF2255;">By Qbic.</span> Qbic represents and warrants that it has the full right and authority to provide the Services in accordance with the terms and conditions of the Terms of Service.</li>
                        <li><span class="font-bold" style="color:#FF2255;">By You.</span> You, on behalf of all Covered Users, represent and warrant that all Covered Users: (i) exclusively own, or have all necessary rights and authorizations to Process or use Covered User Data; (ii) comply with Covered User’s obligations and responsibilities hereunder; and (iii) without limitation, comply with the DPA, SUPs, and all applicable laws. You shall ensure that your agreements with Covered Users sufficiently bind such Covered Users to the obligations and responsibilities imposed upon you hereunder and agree that a breach of the Terms of Service by any Covered User shall constitute a breach by you. In the event a Covered User violates any provision of the Terms of Service, you will be obligated to immediately notify Qbic in writing and terminate such Covered User’s access to your Account and the Services. You are strictly prohibited from permitting, assisting, or enabling any individual or entity not granted permission as an authorized user from accessing or using your Account or any Service. You are responsible and liable for all claims, causes of action, damages, liabilities, penalties, fines, and other losses or liabilities arising out of or relating to the, related to, or associated with a breach, by it or any Covered User, of any of the obligations, responsibilities or assurances described herein. YOU ASSUME TOTAL RESPONSIBILITY FOR THE USE OF THE SERVICES BY ALL COVERED USERS AND EXPRESSLY ACKNOWLEDGE AND UNDERSTAND THAT THE SERVICES ARE NOT DESIGNED, MANUFACTURED, OR INTENDED FOR HIGH RISK ACTIVITIES.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Disclaimer of Warranties.</span> THE SERVICES ARE BEING PROVIDED BY Qbic TO YOU “AS IS” AND “AS AVAILABLE” AND THAT YOU, ON BEHALF OF ALL COVERED USERS, ARE ACCEPTING THE SERVICES WITH ALL FAULTS, WHETHER OR NOT IMMEDIATELY APPARENT. TO THE FURTHEST EXTENT OF APPLICABLE LAW, Qbic AND OUR REPRESENTATIVES (i) EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE,  INCLUDING WITHOUT LIMITATION ALL EXPRESSED OR IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE; (ii) DO NOT WARRANT THAT THE SERVICES WILL MEET YOUR REQUIREMENTS OR OF ANY COVERED USER, OR THAT THE SERVICES WILL BE TIMELY, UNINTERRUPTED, SECURE, ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED; (iii) DO NOT MAKE ANY REPRESENTATIONS REGARDING THE ACCURACY, RELIABILITY, TIMELINESS, OR COMPLETENESS OF THE SERVICES;  AND (iv) ARE NOT RESPONSIBLE OR LIABLE FOR THE DELETION OR FAILURE TO STORE COVERED USER DATA.</li>
                    </ul>
                </div>
                <div id="indemnification">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">10.	Indemnification</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Mutual.</span> Each Party (the “Indemnifying Party”) shall defend, indemnify, and hold the other Party (the “Indemnified Party”)  harmless (collectively “Indemnify”) arising from any loss, lawsuit, liability, damage, cost, and expense, including reasonable attorneys' fees (collectively “Indemnifiable Loss”) for any Dispute related to (i) reckless or intentional misconduct of the Indemnifying Party in connection with the Terms of Service; (ii) the Indemnified Party’s authorized use of the Indemnifying Party’s Intellectual Property except in the instance of a third party Dispute against the Indemnifying Party’s infringement of an Intellectual Property Right; (iii) any Breach or Default in the performance of the obligations of Indemnifying Party hereunder, including without limitation any breach of warranty.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Specific to You.</span> You shall Indemnify Qbic from any Indemnifiable Loss for any Dispute arising from or related to: (i) your sale, resale, or referral of any Service; (ii) damage to property or injury caused by any Covered User Processing of Data in a manner that is inconsistent with the Terms of Service; (iii) any Covered User’s use of any Service in a manner that is inconsistent with the Terms of Service; (iv) your infringement of any third party Intellectual Property relating to Intellectual Property that you allow Qbic to display, disclose, publish, or otherwise use; (v) your failure to provide Notice to Qbic regarding the use of Qbic Services for non-business purposes; and (vi) your failure to provide Notice to Qbic regarding the use of the Services in jurisdictions outside of the United States of America.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Specific to Qbic.</span> Qbic shall Indemnify you from any Indemnifiable Loss for any Dispute arising from or related to (i) damage to property or injury caused by any Covered User Processing Covered User Data in a manner that is consistent with the Terms of Service; and (ii) Qbic’s infringement of any third party Intellectual Property relating to the Services.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Procedures.</span> As a condition precedent of each Indemnifying Party’s obligations, the Indemnified Party (i) must promptly provide Notice to the Indemnifying Party of any Dispute arising out of or relating to an Indemnifiable Loss; (ii) cooperate fully in the defense and/or settlement of any Dispute; and (iii) upon request by the Qbic, grant the Qbic full control of the defense of any applicable Dispute directly related to a Qbic Service. Neither Party shall be permitted to consent to any judgment, settlement, or adverse action without the consent of the other Party, which consent shall not be unreasonably withheld.</li>
                    </ul>
                </div>
                <div id="limitation">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">11.	Limitation of Liabilities</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Waiver.</span> TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL EITHER PARTY, NOR Qbic’S REPRESENTATIVES, BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, REGULATORY, OR CONSEQUENTIAL DAMAGES, INCLUDING WITHOUT LIMITATION ANY LOST REVENUE OR LOST DATA, ARISING OUT OF OR RELATED TO THE SERVICES AND/OR THE TERMS OF SERVICE. THE REMEDIES PROVIDED IN THIS MSA ARE EXCLUSIVE, SHALL APPLY TO ALL CAUSES OF ACTION, AND SHALL APPLY EVEN IF A PARTY SHOULD HAVE KNOWN THAT SUCH DAMAGES WERE POSSIBLE AND EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Limitation on Remedies.</span> TO THE FULLEST EXTENT PERMITTED BY LAW, THE AGGREGATE LIABILITY OF EITHER PARTY AND  Qbic’S REPRESENTATIVES SHALL NOT EXCEED THE AMOUNT OF FEES PAID BY YOU IN THE TWELVE (12) MONTH PERIOD PRECEDING THE DATE A DISPUTE IS ASSERTED BY THE APPLICABLE PARTY. IN NO EVENT SHALL Qbic BE LIABLE FOR ANY DAMAGES WHICH DIRECTLY OR INDIRECTLY RESULT FROM YOUR FAILURE TO PROPERLY CONFIGURE YOUR USE OF THE SERVICES.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Exclusions.</span>  Subsections 11.1 and 11.2 do not apply to any violations of either Party’s indemnification responsibilities or Intellectual Property Rights, nor do they apply to your financial obligations to Qbic.</li>
                    </ul>
                </div>
                <div id="dispute">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">12.	Dispute Resolution</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Generally.</span> The Parties will attempt in good faith to resolve all Disputes arising out of or relating to the Services and/or the Terms of Service. Unless otherwise required by applicable law without the possibility of contractual waiver or limitation, (i) neither Party will bring a Dispute arising out of or related to the Services and/or the Terms of Services more than two years after the cause of action arose, and (ii) after such time limit, any such legal action and all respective rights related to any such action immediately lapse.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Mandatory Arbitration Disclosure and Procedures.</span> ALL COVERED USERS SHALL BE REQUIRED TO BRING ANY DISPUTE AGAINST Qbic IN ACCORDANCE TO THE DISPUTE RESOLUTION PROVISIONS OF THIS MSA, INCLUDING WITHOUT LIMITATION, THE ARBITRATION PROCEDURES AS FOLLOWS:
                            <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                                <li>All Disputes arising from or related to the Services and/or the Terms of Service shall be governed by the laws of the state of New Jersey, United States of America, excluding New Jersey’s conflicts of laws rules.</li>
                                <li>The Parties will attempt in good faith to settle any Dispute within thirty (30) calendar days after the Dispute arises. If the Dispute is not resolved within thirty (30) calendar days, such Dispute shall be resolved by arbitration (each an “Arbitration Proceeding”) by the American Arbitration Association’s International Centre for Dispute Resolution in accordance with its Expedited Commercial Rules in force as of the date of this MSA (“Arbitration Rules”).</li>
                                <li>Each Arbitration Proceeding shall be conducted (i) by a mutually selected arbitrator, (ii) in the English language, and in (iii) Camden County, New Jersey, United States of America. Each Arbitration Proceeding shall be deemed Confidential Information, including without limitation, (i) the existence of, (ii) any Data disclosed during, and (iii) any communications or documents related to, the Arbitration Proceeding.</li>
                                <li>The Parties shall pay all fees and expenses arising from each Arbitration Proceeding in accordance with the Arbitration Rules (collectively “Arbitration Costs”). The arbitrator in each Arbitration Proceeding shall determine the non-prevailing party’s obligation to reimburse the amount paid by the prevailing party for the Arbitration Costs, provided that each Party shall be responsible for such Party’s own lawyers’ and experts’ fees and expenses, regardless of the arbitrator’s final decision regarding the Dispute.</li>
                                <li>Either Party may apply or domesticate to any court of competent jurisdiction located in Camden County, New Jersey, United States of America, for injunctive relief necessary to protect a Party’s rights pending resolution of the applicable Arbitration Proceeding.</li>
                                <li>The arbitral award will be final and binding on the Parties and its execution may be presented in any competent court, including any court with jurisdiction over either Party or any of such Party’s property.</li>
                            </ul>
                        </li>
                        <li><span class="font-bold" style="color:#FF2255;">Class Action Waiver.</span> ALL COVERED USERS SHALL BE REQUIRED TO BRING ANY DISPUTE AGAINST Qbic IN EACH SUCH COVERED USER’S INDIVIDUAL CAPACITY AND SHALL NOT BRING ANY DISPUTE AGAINST Qbic AS A MEMBER OF ANY PURPORTED CLASS, COLLECTIVE, REPRESENTATIVE, MULTIPLE PLAINTIFF, OR SIMILAR PROCEEDING (COLLECTIVELY “CLASS ACTION”). ANY CLAIM THAT ALL OR PART OF THIS CLASS ACTION WAIVER IS UNENFORCEABLE, UNCONSCIONABLE, VOID, OR VOIDABLE MAY BE DETERMINED ONLY BY A COURT OF COMPETENT JURISDICTION AND NOT BY AN ARBITRATOR. TO THE FULLEST EXTENT PERMITTED BY LAW, ALL COVERED USERS EXPRESSLY AND IRREVOCABLY WAIVES ANY ABILITY TO MAINTAIN ANY CLASS ACTION IN ANY FORUM IN CONNECTION WITH ANY DISPUTE ARISING FROM THE TERMS OF SERVICE.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Jury Trial Waiver.</span> TO THE FULLEST EXTENT PERMITTED BY LAW, THE ALL COVERED USERS EXPRESSLY AND IRREVOCABLY WAIVE THEIR RESPECTIVE RIGHTS TO A JURY TRIAL FOR ANY DISPUTE ARISING FROM THE TERMS OF SERVICE.</li>
                    </ul>
                </div>
                <div id="confidential">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">13.	Confidential Information</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Each Party shall only use the other party’s Confidential Information in connection with Qbic’s provision of the Services to you or your use of the Services in accordance with the Terms of Service.  The recipient of Confidential Information not disclose the disclosing Party’s Confidential Information to any third party unless such third party is providing services or functions in support of a Party’s exercise of its rights or performance of its obligations hereunder and is bound in writing by confidentiality and limited use restrictions substantially similar to those required hereunder or otherwise commercially reasonable and sufficient to obtain a substantially similar level of protection. The limitations on disclosure or use of Confidential Information shall not apply to information which: (i) is rightfully obtained by the recipient without breach of any confidentiality obligation; (ii) is or becomes known to the public through no act or omission of the recipient; (iii) the recipient obtains independently without using Confidential Information of the other Party; or (iv) is disclosed in response to a valid court or governmental order (such as a subpoena).
                    </p>
                </div>
                <div id="termination">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">14.	Term and Termination</span>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">Continuation.</span> his MSA shall commence on the Effective Date and continue until this MSA is terminated in accordance with the provisions herein.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Termination.</span> Either Party may terminate this MSA upon written notice if the other Party breaches any material provision of the Terms of Service and fails, within thirty (30) days after receipt of Notice to correct the breach. Termination of this MSA shall result in automatic corresponding termination of all Service Orders and SPA then in effect. Either Party may terminate this MSA in writing at any point when there is no Service Order or SPA then in effect. In addition, (i) Qbic may terminate this MSA for Qbic’s convenience at any time without liability to any Covered Users and (ii) you may terminate this MSA for its convenience upon full and final payment of all outstanding Fees.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Suspension.</span> Qbic may suspend any Covered User’s rights of use the Services immediately: (i) if you are delinquent or deficient in your payment obligations; (ii) if Qbic reasonably believes that any Covered User is misusing any Qbic Service in violation of applicable law or in breach of the Terms of Service; (iii) if any Covered User Data infringes a third party’s intellectual property or otherwise proprietary rights; (iv) if any Covered User’s use of any Covered User Data or the Services presents a security or liability risk; or (v) if Qbic is required by law, court order, or a regulatory or government body to suspend the Services.</li>
                        <li><span class="font-bold" style="color:#FF2255;">Effect of Termination.</span> Upon termination of this MSA, all rights and obligations under the Terms of Service shall automatically terminate except as otherwise provided in the Terms of Service.
                            <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                                <li>Fees. In the event of a termination of this MSA, or any SPA or Service Order effectuated hereunder, as a result of Qbic’s material breach or default of the Terms of Service, you shall be obligated to render payment to Qbic for all outstanding Fees prior to the date of such breach or default. In the event of a termination of this MSA, or any SPA or Service Order effectuated hereunder, not the result of Qbic’s material breach or default of the Terms of Service, you shall be obligated to render payment to Qbic for all outstanding Fees as of the termination date.</li>
                                <li>Data. You shall return all of Qbic’s proprietary materials, Confidential Information, and other property, and immediately cease all access and use of the Service. Upon termination, Qbic may, without obligation to do so and unless otherwise required by applicable law, delete the  Covered User Data in its entirety without liability. Qbic may maintain a copy of the Covered User Data in accordance with Qbic’s then-current data retention practices and as otherwise expressly authorized hereunder. The provisions of the Terms of Service which relate to confidentiality, intellectual property ownership, indemnity, limitations of liability, disclaimers, and payment obligations, along with terms which expressly or by their nature should reasonably survive termination, shall survive expiration or termination hereof.</li>
                            </ul>
                        </li>
                        <li><span class="font-bold" style="color:#FF2255;">Effect of Suspension.</span> In the event of a suspension of any Service in accordance with the provisions the Terms of Service, then with respect to the period of the suspension, you shall remain responsible for the payment of all Fees and Qbic shall not be liable to you for any service credits or other remedies which otherwise would have been available under the Terms of Service.</li>
                    </ul>
                </div>
                <div id="cooperation">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">15.	Cooperation</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Audit Rights. You shall cooperate with Qbic’s investigation of any suspected violation of the Terms of Service. Without obligation to do so, Qbic shall have the right to audit Covered User’s use of the Services from time to time.
                    </p>
                </div>
                <div id="contractor">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">16.	Independent Contractor Relationship</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        No Third Party Beneficiaries. The Parties are independent contractors and nothing contained in the Terms of Service shall be construed to create an association, trust, partnership, agency, or joint venture between the parties.  The Terms of Service do not and are not intended to confer any rights or remedies, express or implied, upon any person other than the Parties hereto. Nothing in the Terms of Service shall be interpreted or construed as creating or establishing any employment or agency relationship between you and Qbic.  The Parties acknowledge and agree that you are not an employee of Qbic for any purpose, including without limitation, (i) state, federal or international taxes, (ii) workers’ compensation, social security, group insurance, retirement, or other contributing benefits, and (iii) sick leave or vacation pay customarily provided by an employer with respect to an employee. Each Party shall bear full and sole responsibility for its own expenses, liabilities, and costs of operation. Neither Party will have the authority to, and will not purport to, enter into any contract on behalf of the other Party, or commit it to any obligation.
                    </p>
                </div>
                <div id="assignment">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">17.	Assignment</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        You may not assign or transfer any part of this MSA without the prior written consent of Qbic. Qbic may assign the Terms of Service to a Representative or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets or a controlling interest in its ownership.
                    </p>
                </div>
                <div id="force-majeure">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">18.	Force Majeure</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Qbic and our Representatives shall not be liable for any failure to perform any obligation under the Terms of Service in instances where such failure arising from or is related to any cause beyond its reasonable control,
                    </p>
                </div>
                <div id="restrictions">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">19.	Trade Restrictions</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        You shall not transfer, import, export, sell, resell, use, or otherwise use, permit, or facilitate any other party’s use of the Services in any manner which would cause any Covered User or Qbic to breach any applicable US trade control laws, orders, or regulations. In addition, you shall not, directly or indirectly export or re-export the Services: (i) to any country to which the is subject to US embargo (including, for these purposes, any national or resident of any such country); or (ii) to anyone on the US Treasury Department’s List of Specially Designated Nationals and Blocked Persons, List of Specially Designated Terrorists, List of Specially Designated Narcotics Traffickers, or the US Department of Commerce Bureau of Industry and Security Denied Persons List.
                    </p>
                </div>
                <div id="governing">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">20.	Governing Law and Jurisdiction</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        The laws of the State of New Jersey shall govern the interpretation and enforcement of this MSA and any dispute arising out of or related hereto, without regard to its conflict of laws principles.  The parties irrevocably submit to the exclusive jurisdiction of the state and federal courts located in Camden County, New Jersey with respect to any Dispute arising out of or relating to the Terms of Service.
                    </p>
                </div>
                <div id="government-customers">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">21.	Government Customers</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        In instances of the Services being provided to a US governmental entity in its governmental capacity, including any related technical data or accompanying documentation, the Services shall be considered “commercial items” and “technical data” as defined in 48 C.F.R. §2.101 with the same restrictions, limitations, and rights which are set forth in this MSA. If any Covered User uses the Services on behalf of a governmental entity and any or all of this MSA fails to meet that government’s needs or is inconsistent in any respect with law, the Covered Users, as applicable, shall immediately discontinue use of the Services.
                    </p>
                </div>
                <div id="disclosure">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">22.	Disclosure to Law Enforcement or Judicial Proceedings</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        You agree that Qbic may disclose any or all Covered User Data to any court or law enforcement agency or authority that issues a valid court order or subpoena without seeking your consent or notification.  Qbic may charge you, and you shall reimburse Qbic, for excessive costs incurred by Qbic in complying with such order or subpoena, including costs of attorneys for time spent retrieving, reviewing, and preparing responsive documents.
                    </p>
                </div>
                <div id="waiver">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">23.	Waiver</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        The failure of any Party in any one or more instances to insist upon strict performance of any terms or provisions of this MSA, or any DPA, SLA, SPA, SUP, and Service Order effectuated hereunder, or to exercise any option or remedy which is conferred in the Terms of Service, shall not be construed as a waiver, or relinquishment to any extent of the right to assert or rely upon any such terms, provisions, options, or remedies on any future occasion. No waiver by either Party hereunder shall be effective unless agreed to pursuant to a writing signed by a duly authorized representative of the Party granting the waiver.
                    </p>
                </div>
                <div id="severability">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">24.	Severability</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Each provision of this MSA and of any DPA, NDA, SLA, SPA, SUP, or Service Order effectuated hereunder, shall be considered separable; and if, for any reason, any provision of the Terms of Service is determined by a court of competent jurisdiction to be in violation of any statute, regulation, rule, order or decree of any governmental authority, such determination shall not affect the enforceability of the remainder of the Terms of Service or the validity, lawfulness, or enforceability of such provision in any other jurisdiction. If any court of competent jurisdiction shall deem any provision of the Terms of Service too restrictive, the other provisions of the Terms of Service shall stand, and the court shall modify the provisions at issue to the point of greatest restriction permissible by applicable law.
                    </p>
                </div>
                <div id="construction">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">25.	Construction</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        If an ambiguity or question of intent or interpretation arises, the Terms of Service shall be construed as if drafted jointly by the Parties and no presumption or burden of proof shall arise favoring or disfavoring any Party by virtue of its authorship of any of the provisions of the Terms of Service. Words used in the Terms of Service in the singular, where the context so permits, shall be deemed to include the plural and vice versa. The definitions of words in the singular in the Terms of Service shall apply to such words when used in the plural where the context so permits and vice versa.
                    </p>
                </div>
                <div id="agreement">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">26.	Entire Agreement</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        This MSA, and DPA, NDA, SLA, SPAs, SUPs, and Service Orders effectuated hereunder represents the entire agreement between you and Qbic with respect to the Services and supersedes all prior oral and written understandings, communications, or agreements between you and Qbic regarding that subject matter. No amendment to or modification of this MSA will be valid or binding unless it is in writing and executed by authorized representatives of both Parties.
                    </p>
                </div>
                <div id="definitions">
                    <span class="block mt-10 text-2xl lg:text-4xl font-bold">27.	Definitions</span>
                    <p class="mt-8 lg:font-medium text-xl lg:text-2xl">
                        Various capitalized terms which are used throughout this MSA are defined in the section in which they are first used or as follows:
                    </p>
                    <ul class="mt-4 lg:font-medium text-xl lg:text-2xl">
                        <li><span class="font-bold" style="color:#FF2255;">“Account”</span> means the online portal provided by Qbic which permits you to register for and administer the use of Services by Covered Users.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Confidential Information”</span> means non-public information of a Party which is provided to the other Party hereunder and which is either designated as confidential or of a type which should be recognized by a commercially reasonable party as confidential.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Covered User Data”</span> collectively means any Data that is Processed or otherwise provided to Qbic by any Covered User.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Data”</span> means any individual or collection of text, number, symbol, audio, software, file, information, or content that is capable of being Processed.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Data Processing Addendum” or “DPA”</span> can be found <a href="https://www.linode.com/legal-dpa/">here</a> and is incorporated in its entirety to this MSA by this reference.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Dispute”</span>  includes any and all allegations, conflicts, claims, controversies, and other legal causes of action, whether alleged or not alleged, known or unknown, vested or contingent and/or asserted or not asserted, arising or occurring as between the Parties, Representatives, or End Users.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“End User”</span> means any individual or entity, including without limitation your third party users and such third party users’ Representatives, that is directly or indirectly permitted by you to use or access your Account or the Services.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Fee”</span> means any charge and otherwise cost arising from or related to the Covered User’s use of the Services</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Intellectual Property”</span> means any and all tangible or intangible property, including without limitation devices, machines, components, parts, methods, procedures, data, information, inventions, discoveries, works of authorship, designs, and derivative works.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Intellectual Property Right”</span> means any and all of the universal legal rights afforded to the Intellectual Property based on statute or common law, including without limitation, patents, copyrights, and trade secrets.</li>
                        <li><span class="font-bold" style="color:#FF2255;">"Qbic"</span> shall mean (i) Qbic LLC if your Account billing address is located in the United States of America or India or (ii) Qbic International Services Company if your Account billing address is not located in the United States of America or India.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Notice”</span> shall mean any document, request, demand, and otherwise communication required by the Terms of Service, each of which shall be in writing and delivered (i) in person or by courier, (ii) first-class registered mail or certified mail, or (iii) electronically by email. Qbic shall deliver all Notices to the address and point of contact listed in your Account, and you may deliver all Notices to Qbic by email to support@Qbic.cloud or by physical mail at 249 Arch Street, Philadelphia, Pennsylvania 19106.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Party”</span>  means each of you and Qbic.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Process” and “Processed” and “Processing”</span>  shall collectively mean any (i) direct or indirect and (ii) manual or automated access, acquisition, collected, development, implementation, maintenance, transmission, use, and otherwise performance of any operation or set of operations upon Data.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Representative”</span>  includes any parent company, affiliate, subsidiary, owner, director, manager, employee, professional advisor, director, officer, trustee, successor, assign, agent, administrator, executor, or personal representative of a Party. With respect to Qbic, a "Representative" shall also include any authorized QbicThird Party Service Provider that is not listed on the Qbic Marketplace.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Service”</span>  means the cloud hosting services, computing resources, and other services made available by Qbic for purchase and use by Covered Users, including without limitation, any website, product, software, hardware, application, API, machine, equipment, documentation, or technology authorized by Qbic to provide or make available the products set forth at https://www.Qbic.cloud.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Service Order” or “SO”</span>  means any Services agreement offered by Qbic, accepted by Client, and mutually consented to by the Parties arising out of or relating to this MSA.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Service Level Addenda” or “SLA”</span>  means any applicable service level agreement set forth at www.Qbic.cloud.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Supplemental Program Addendum” or “SPA”</span>  means any mutually executed addenda governing your participation in any Qbic program set forth at www.Qbic.cloud.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Supplemental Use Policy” or “SUP”</span>  means any policy governing the use of the Qbic Services found at www.Qbic.cloud, including without limitation: Qbic’s Acceptable Use Policy, Privacy Policy, Reseller Policy, and EU Model Contract, each of which is incorporated into this MSA by this reference, as amended by Qbic from time to time, with or without notice.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Terms of Service”</span>  collectively means the MSA, DPA, SLA, SPAs SUPs, and Service Orders.</li>
                        <li><span class="font-bold" style="color:#FF2255;">“Third Party Service Provider” or “TSP”</span>  means any contractor, subcontractor, processor, subprocessor, supplier, and otherwise vendor of a Party, including without limitation third party contributors, developers, publishers, and producers.</li>
                    </ul>
                </div>
            </div>
        </div>

    </section>
</main>
<?php get_footer(); ?>